apiVersion: v1
kind: Service
metadata:
  name: kubia-http
  labels:
    name: kubia-http
    env: dev
    purpose: study
spec:
  type: LoadBalancer
  externalIPs:
    - 192.168.251.2
  selector:
    app: kubia
  ports:
    - protocol: TCP
      port: 10887
      targetPort: 10887
