apiVersion: batch/v1
kind: Job
metadata:
  name: multi-batch-job
spec:
  ttlSecondsAfterFinished: 30
  completions: 5
  parallelism: 2
  activeDeadlineSeconds: 600 # 任务最多处理600秒，超时自动停止并失败
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: main
          image: luksa/batch-job
