apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vod-etcd-claim
  namespace: apisix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi