apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-etcd-0
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-05f66195cd82bd473::fsap-0af43441c9ffcf43d

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-etcd-1
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-05f66195cd82bd473::fsap-0100cc6b746b6d12d
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-etcd-2
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-05f66195cd82bd473::fsap-0b309dbdbd6471b7f
    parameters:
