apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hotkey-worker-hpa
  namespace: hotkey
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hotkey-worker
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75